In [1]:
import numpy as np # 배열형식의 데이터 관리 제고으 고성능 연산

In [5]:
# 배열 생성
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.dtype)
print(arr1.ndim)
print(arr1.shape)

[[1 2 3]
 [4 5 6]]
int32
2
(2, 3)


In [9]:
# 배열 생성2
arr2=np.arange(1,10).reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
# 배열 생성3
arr3=np.random.randn(4,4)
print(arr3)

[[-0.8800953   0.75431726  1.2800591  -0.42657823]
 [-3.338601   -0.543695   -1.16016737  0.76301167]
 [-0.52485834  0.45292319  0.35527562 -0.06678272]
 [-0.43192026  2.36638091 -0.45819925  0.4763641 ]]


In [105]:
# 배열 생성4 : 임의의 값 1-~50 사이의 값을 발생하여 4x4 배열 생성
arr4=np.random.randint(1,51,16).reshape(4,4)
print(arr4)

[[39 16 28 19]
 [10 26 14  7]
 [ 5 37  9  2]
 [50  7 31  9]]


In [65]:
# 검색
arr4

array([[ 1, 44, 15, 44],
       [24, 21, 39, 28],
       [11,  6, 40, 34],
       [31, 21, 31,  4]])

In [66]:
arr4[0] # 1행 출력

array([ 1, 44, 15, 44])

In [49]:
arr4[1,3] # 특정 위치 출력

28

In [68]:
arr4[0:4,1:3] # 특정 범위 출력

array([[44, 15],
       [21, 39],
       [ 6, 40],
       [21, 31]])

In [71]:
arr5=arr4>20 # 배열값 조건식
print(arr5)

[[False  True False  True]
 [ True  True  True  True]
 [False False  True  True]
 [ True  True  True False]]


In [92]:
arr6=arr4.copy()
arr6

array([[ 1, 44, 15, 44],
       [24, 21, 39, 28],
       [11,  6, 40, 34],
       [31, 21, 31,  4]])

In [93]:
arr6[0,2]=30
arr6

array([[ 1, 44, 30, 44],
       [24, 21, 39, 28],
       [11,  6, 40, 34],
       [31, 21, 31,  4]])

In [94]:
arr6[arr6<=20]=0 #f 각 셀마다 조건식을 확인하여 값을 할당
arr6

array([[ 0, 44, 30, 44],
       [24, 21, 39, 28],
       [ 0,  0, 40, 34],
       [31, 21, 31,  0]])

In [95]:
b=arr6[1] # b가 별개의 객체가 아닌 참조객체로 동작하여, 원래 데이터 arr6에도 영향을 끼친다
print(b)
b[0]=100
print(b)
print(arr6)

[24 21 39 28]
[100  21  39  28]
[[  0  44  30  44]
 [100  21  39  28]
 [  0   0  40  34]
 [ 31  21  31   0]]


In [106]:
# 통계함수
arr4

array([[39, 16, 28, 19],
       [10, 26, 14,  7],
       [ 5, 37,  9,  2],
       [50,  7, 31,  9]])

In [101]:
print(np.sum(arr4)) #배열 총합
print(np.sum(arr4, axis=0)) #세로줄 합계
print(np.sum(arr4, axis=1)) #가로줄 합계

394
[ 67  92 125 110]
[104 112  91  87]


In [108]:
np.max(arr4, axis=0) #세로줄에서 최대값

array([50, 37, 31, 19])

In [114]:
np.argmax(arr4, axis=0) #세로줄에서 최대값의 인덱스

array([3, 2, 3, 0], dtype=int64)

In [115]:
np.cumsum(arr4, axis=0) # 세로줄의 값을 적산하여 표출

array([[ 39,  16,  28,  19],
       [ 49,  42,  42,  26],
       [ 54,  79,  51,  28],
       [104,  86,  82,  37]], dtype=int32)